"""FastAPI routes for demand forecasting and operational risk intelligence."""

from datetime import date
from typing import List, Optional
from fastapi import APIRouter, Depends, HTTPException, Query, status

from src.api.auth import verify_api_key
from src.api.schemas import (
    ExecutiveSummaryResponse,
    ForecastItemResponse,
    ForecastResponse,
    HealthResponse,
    InventoryItemResponse,
    InventoryResponse,
    RecommendationItemResponse,
    RecommendationResponse,
    RiskItemResponse,
    RiskResponse,
)
from src.api.service import IntelligenceService, get_intelligence_service

router = APIRouter()


@router.get(
    "/health",
    response_model=HealthResponse,
    summary="Service Health & Liveness Check",
    tags=["System"],
)
def get_health(service: IntelligenceService = Depends(get_intelligence_service)) -> HealthResponse:
    """Verify API availability, engine version, database connectivity, and analysis reference date (Public)."""
    try:
        service.initialize()
        return HealthResponse(
            status="healthy",
            engine_version="1.0.0",
            as_of_date=service.as_of_date,
            database_connected=True,
        )
    except Exception as exc:
        raise HTTPException(
            status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
            detail=f"Database or intelligence service unavailable: {str(exc)}",
        )


@router.get(
    "/summary",
    response_model=ExecutiveSummaryResponse,
    summary="Executive Intelligence KPI Summary",
    tags=["Executive Overview"],
    dependencies=[Depends(verify_api_key)],
)
def get_executive_summary(
    service: IntelligenceService = Depends(get_intelligence_service),
) -> ExecutiveSummaryResponse:
    """Retrieve network-wide executive KPIs including risk counts, excess capital, and model accuracy."""
    summary_dict = service.get_executive_summary()
    return ExecutiveSummaryResponse(**summary_dict)


@router.get(
    "/forecast",
    response_model=ForecastResponse,
    summary="Multi-Horizon Demand Forecasts",
    tags=["Forecasting"],
    dependencies=[Depends(verify_api_key)],
)
def get_forecasts(
    location_id: Optional[str] = Query(None, description="Optional facility ID (e.g. LOC-ST-01)"),
    product_id: Optional[str] = Query(None, description="Optional product SKU ID (e.g. PRD-BEV-001)"),
    horizon_days: int = Query(30, ge=1, le=30, description="Forecast horizon in days (1 to 30)"),
    service: IntelligenceService = Depends(get_intelligence_service),
) -> ForecastResponse:
    """Retrieve daily point demand forecasts generated by the champion LightGBM model."""
    if location_id and not service.is_valid_location(location_id):
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail=f"Location '{location_id}' not found.")
    if product_id and not service.is_valid_product(product_id):
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail=f"Product '{product_id}' not found.")

    df = service.get_forecasts(
        location_id=location_id,
        product_id=product_id,
        horizon_days=horizon_days,
    )
    items = [ForecastItemResponse(**row) for row in df.to_dict(orient="records")]
    return ForecastResponse(
        total_items=len(items),
        horizon_days=horizon_days,
        items=items,
    )


@router.get(
    "/risk",
    response_model=RiskResponse,
    summary="Predictive Stockout & Excess Inventory Risks",
    tags=["Risk Intelligence"],
    dependencies=[Depends(verify_api_key)],
)
def get_risk_positions(
    location_id: Optional[str] = Query(None, description="Optional facility ID (e.g. LOC-ST-01)"),
    product_id: Optional[str] = Query(None, description="Optional product SKU ID (e.g. PRD-BEV-001)"),
    risk_tier: Optional[str] = Query(None, description="Risk severity tier (CRITICAL, HIGH, MEDIUM, LOW)"),
    service: IntelligenceService = Depends(get_intelligence_service),
) -> RiskResponse:
    """Retrieve SKU x Location predictive risk scores, exact days-to-runout, and root-cause attributions."""
    if location_id and not service.is_valid_location(location_id):
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail=f"Location '{location_id}' not found.")
    if product_id and not service.is_valid_product(product_id):
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail=f"Product '{product_id}' not found.")

    df = service.get_risk_positions(
        location_id=location_id,
        product_id=product_id,
        risk_tier=risk_tier,
    )
    items = [RiskItemResponse(**row) for row in df.to_dict(orient="records")]

    crit = sum(1 for it in items if it.stockout_risk_tier == "CRITICAL")
    high = sum(1 for it in items if it.stockout_risk_tier == "HIGH")
    med = sum(1 for it in items if it.stockout_risk_tier == "MEDIUM")
    low = sum(1 for it in items if it.stockout_risk_tier == "LOW")
    tot_cap = round(sum(it.capital_at_risk for it in items), 2)

    return RiskResponse(
        total_positions=len(items),
        critical_count=crit,
        high_count=high,
        medium_count=med,
        low_count=low,
        total_capital_at_risk=tot_cap,
        positions=items,
    )


@router.get(
    "/inventory",
    response_model=InventoryResponse,
    summary="Inventory Health Positions",
    tags=["Inventory Health"],
    dependencies=[Depends(verify_api_key)],
)
def get_inventory_health(
    location_id: Optional[str] = Query(None, description="Optional facility ID filter"),
    product_id: Optional[str] = Query(None, description="Optional product ID filter"),
    service: IntelligenceService = Depends(get_intelligence_service),
) -> InventoryResponse:
    """Retrieve baseline inventory health positions, 30-day demand averages, and days-of-supply."""
    if location_id and not service.is_valid_location(location_id):
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail=f"Location '{location_id}' not found.")
    if product_id and not service.is_valid_product(product_id):
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail=f"Product '{product_id}' not found.")

    df = service.get_inventory_health(location_id=location_id, product_id=product_id)
    items = [InventoryItemResponse(**row) for row in df.to_dict(orient="records")]
    return InventoryResponse(
        total_items=len(items),
        items=items,
    )


@router.get(
    "/recommendations",
    response_model=RecommendationResponse,
    summary="Prescriptive Replenishment Actions",
    tags=["Prescriptive Recommendations"],
    dependencies=[Depends(verify_api_key)],
)
def get_recommendations(
    location_id: Optional[str] = Query(None, description="Optional facility ID filter"),
    product_id: Optional[str] = Query(None, description="Optional product ID filter"),
    action_type: Optional[str] = Query(None, description="Action type filter (DC_TRANSFER, PURCHASE_ORDER, HOLD_ORDER)"),
    priority_tier: Optional[str] = Query(None, description="Priority tier filter (URGENT, HIGH, MEDIUM, LOW)"),
    service: IntelligenceService = Depends(get_intelligence_service),
) -> RecommendationResponse:
    """Retrieve explainable prescriptive replenishment recommendations prioritized by revenue and risk impact."""
    if location_id and not service.is_valid_location(location_id):
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail=f"Location '{location_id}' not found.")
    if product_id and not service.is_valid_product(product_id):
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail=f"Product '{product_id}' not found.")

    df = service.get_recommendations(
        location_id=location_id,
        product_id=product_id,
        action_type=action_type,
        priority_tier=priority_tier,
    )
    items = [RecommendationItemResponse(**row) for row in df.to_dict(orient="records")]

    urg = sum(1 for it in items if it.priority_tier == "URGENT")
    hi = sum(1 for it in items if it.priority_tier == "HIGH")
    med = sum(1 for it in items if it.priority_tier == "MEDIUM")
    lo = sum(1 for it in items if it.priority_tier == "LOW")

    return RecommendationResponse(
        total_recommendations=len(items),
        urgent_count=urg,
        high_count=hi,
        medium_count=med,
        low_count=lo,
        recommendations=items,
    )
